### ISSUE TITLE
ImportError: cannot import name 'region' from 'pysot.utils' (./pysot/utils/__init__.py)

### ISSUE THREAD

**Issue by ghost** [StrangerZhang/pysot-toolkit#12]

**Comment by 17818587795** [comment]
ImportError: cannot import name 'region' from 'pysot.utils' (./pysot/utils/__init__.py)
how to solve the problem?

**Comment by sbshah97** [comment]
Facing the same issue. How was this resolved any pointers?

**Comment by hongsheng-Z** [comment]
cd pysot/utils/
python setup.py build_ext --inplace

It's that working

> Facing the same issue. How was this resolved any pointers?
