### ISSUE TITLE
The report of vot-lt is different from that generated by vot-toolkit.

### ISSUE THREAD

**Issue by lawpdas** [StrangerZhang/pysot-toolkit#2]
The F-score of some trackers is different from that computed by vot-toolkit. And the PR-plot is also different.
![image](https://user-images.githubusercontent.com/5070053/54604946-fc438c80-4a82-11e9-892f-58e24d3f1aa2.png)
![image](https://user-images.githubusercontent.com/5070053/54605139-8d1a6800-4a83-11e9-973e-7ad16a1c236a.png)

**Comment by Dtappledoghuati** [comment]
I have trouble in loading the vot dataset.

python bin/eval.py   --dataset_dir datasets/VOT2018   --dataset VOT2018   --
tracker_result_dir results    --trackers ECO UPDT SiamRPNpp
loading VOT2018:   0%|                                                       | 0loading VOT2018:   0%|                                                | 0/60 [00:00<?, ?it/s, ants1]Traceback (most recent call last):
  File "bin/eval.py", line 134, in <module>
    dataset = VOTDataset(args.dataset, root)
  File "./pysot/datasets/vot.py", line 119, in __init__
    load_img=load_img)
  File "./pysot/datasets/vot.py", line 54, in __init__
    img = np.array(Image.open(img_name), np.uint8)
  File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/PIL/Image.py", line 2770, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/VOT2018/datasets/VOT2018/ants1/color/00000001.jpg'
loading VOT2018:   0%|                                                | 0/60 [00:00<?, ?it/s, ants1]
