### ISSUE TITLE
Problem about ‘SyntaxError: invalid syntax’ when running 'eval.py'

### ISSUE THREAD

**Issue by universefall** [StrangerZhang/pysot-toolkit#4]
I run 'eval.py' and it shows following error:
Traceback (most recent call last):
  File "bin/eval.py", line 12, in <module>
    from pysot.evaluation import OPEBenchmark, AccuracyRobustnessBenchmark, EAOBenchmark, F1Benchmark
  File ".\pysot\evaluation\__init__.py", line 1, in <module>
    from .ar_benchmark import AccuracyRobustnessBenchmark
  File ".\pysot\evaluation\ar_benchmark.py", line 107
    row += f'{Fore.RED}{accuracy_str}{Style.RESET_ALL}|'
                                                       ^
SyntaxError: invalid syntax

could anyone help me? pls.  Is it related to python verison?

**Comment by StrangerZhang** [comment]
I only test on python 3, what's your python version?

**Comment by universefall** [comment]
> I only test on python 3, what's your python version?

My python version is 3.5.6

**Comment by universefall** [comment]
Another question, should the OTB result file be saved as .mat or .txt? How about VOT result?

**Comment by StrangerZhang** [comment]
If you want to evaluate on official MATLAB toolkit, you should save as .mat

VOT format is .txt

**Comment by universefall** [comment]
> If you want to evaluate on official MATLAB toolkit, you should save as .mat
> 
> VOT format is .txt

Forget the official VOT-toolkit, a number of problem happened in that platform.

**Comment by universefall** [comment]
I also test on python 2.7 and still happened same problem

**Comment by wwdguu** [comment]
python 3.5 are not supported to this.
You may chang the code f'{Fore.RED}{accuracy_str}{Style.RESET_ALL}|'
into row += '{}{}{}|'.format(Fore.RED,accuracy_str,Style.RESET_ALL)

**Comment by universefall** [comment]
> python 3.5 are not supported to this.
> You may chang the code f'{Fore.RED}{accuracy_str}{Style.RESET_ALL}|'
> into row += '{}{}{}|'.format(Fore.RED,accuracy_str,Style.RESET_ALL)

thanks a lot, I will try

**Comment by universefall** [comment]
> python 3.5 are not supported to this.
> You may chang the code f'{Fore.RED}{accuracy_str}{Style.RESET_ALL}|'
> into row += '{}{}{}|'.format(Fore.RED,accuracy_str,Style.RESET_ALL)

It works! Thank u!
