### ISSUE TITLE
How to evaluate trackers?

### ISSUE THREAD

**Issue by TSSSS4** [StrangerZhang/pysot-toolkit#5]
In "Get Tracking Results of Your Own Tracker" part, the tracking results are saved in pred_bboxes, what's next? How to save these results, and in what format?
Thanks

**Comment by wwdguu** [comment]
You may save the result as .txt file. I have  released a repo called  pyCFTrackers,  you can go to my page and check the repo as ref.

**Comment by 280085871** [comment]
Hi,how can I get more deeptrackers' testing result ? for example,DaSiamRPN,SINT,SiamFC,etc.
