### ISSUE TITLE
Number of frames discrepancy for video `Tiger1` in OTB100

### ISSUE THREAD

**Issue by bkkm78** [StrangerZhang/pysot-toolkit#6]
The original `groundtruth_rect.txt` file for video `Tiger1` contains 354 frames, but `OTB100.json` hosted on baidu pan contains only 349 frames for it. Is there an update to the original annotations?

**Comment by StrangerZhang** [comment]
Yes, the actual frames used in the original matlab toolkit version is 349 frames.

**Comment by bkkm78** [comment]
Thanks for the clarification!
